### ISSUE TITLE
소셜로그인 관련 기능 개발: 진행중

### ISSUE THREAD

**Issue by sujeong11** [Freeder-corp/bucl-server#6]
## ✅ TODO
- [x] jwt 환경 구축
- [x] 카카오 로그인 기능
- [ ] 애플 로그인 기능
- [x] 토큰 재발급 기능
- [x] 로그아웃 기능
- [x] 회원 탈퇴 기능
